"""
core/incident_manager.py
────────────────────────
Tracks every incident from detection through containment to close.

State machine:
    OPEN → CONTAINED → CLOSED
    OPEN → DISMISSED            (MEDIUM alert user dismissed)
    OPEN → FAILED               (containment attempted but all actions failed)

Storage:
  • In-memory dict (fast lookup by ID, lost on crash — that's OK for v1)
  • JSON file per incident under %APPDATA%/MalTracer/incidents/<INC-ID>.json
    Written on every state transition so the file is always current.

Thread safety:
  • A single RLock guards both the in-memory dict and file writes.
  • All public methods are safe to call from any thread.

Incident ID format:  INC-YYYYMMDD-xxxxxxxx
(generated by detection_engine/engine.py and stamped on the event dict)
"""

import json
import threading
import uuid
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

from logging_system.logger import get_logger
from utils.constants import INCIDENTS_DIR, INCIDENT_ID_PREFIX

logger = get_logger(__name__)

# Valid states and allowed transitions
_STATES = {"OPEN", "CONTAINED", "DISMISSED", "FAILED", "CLOSED"}

_ALLOWED_TRANSITIONS: dict[str, set[str]] = {
    "OPEN":      {"CONTAINED", "DISMISSED", "FAILED", "CLOSED"},
    "CONTAINED": {"CLOSED"},
    "DISMISSED": {"CLOSED"},
    "FAILED":    {"CLOSED"},
    "CLOSED":    set(),   # terminal — no further transitions
}


class Incident:
    """
    Data class for a single incident.
    All fields are plain Python types for easy JSON serialisation.
    """

    __slots__ = (
        "incident_id",
        "state",
        "created_at",
        "updated_at",
        "threat_level",
        "risk_score",
        "threat_category",
        "source",
        "process_name",
        "pid",
        "file_path",
        "remote_ip",
        "containment",
        "history",
        "notes",
    )

    def __init__(self, event: dict):
        now = datetime.now(timezone.utc).isoformat()

        self.incident_id     = event["incident_id"]
        self.state           = "OPEN"
        self.created_at      = event.get("timestamp", now)
        self.updated_at      = now

        # Detection fields
        self.threat_level    = event.get("threat_level", "LOW")
        self.risk_score      = event.get("risk_score", 0)
        self.threat_category = event.get("threat_category", "unknown")
        self.source          = event.get("source", "unknown")
        self.process_name    = event.get("process_name")
        self.pid             = event.get("pid")
        self.file_path       = event.get("file_path")
        self.remote_ip       = event.get("remote_ip")

        # Filled in later by containment / analyst
        self.containment: Optional[dict] = None
        self.notes: list[str] = []

        # Immutable audit log of every state transition
        self.history: list[dict] = [
            {
                "ts":        now,
                "from_state": None,
                "to_state":   "OPEN",
                "reason":     "Incident created by detection engine",
            }
        ]

    def to_dict(self) -> dict:
        return {
            "incident_id":     self.incident_id,
            "state":           self.state,
            "created_at":      self.created_at,
            "updated_at":      self.updated_at,
            "threat_level":    self.threat_level,
            "risk_score":      self.risk_score,
            "threat_category": self.threat_category,
            "source":          self.source,
            "process_name":    self.process_name,
            "pid":             self.pid,
            "file_path":       self.file_path,
            "remote_ip":       self.remote_ip,
            "containment":     self.containment,
            "notes":           self.notes,
            "history":         self.history,
        }


class IncidentManager:
    """
    Creates, tracks, and transitions incidents.

    One shared instance is created by core/engine.py and passed to the
    detection engine (which stamps incident IDs) and the containment engine
    (which calls transition() when containment completes).
    """

    def __init__(self, incidents_dir: Path = INCIDENTS_DIR):
        self._incidents: dict[str, Incident] = {}
        self._lock = threading.RLock()
        self._incidents_dir = Path(incidents_dir)

        try:
            self._incidents_dir.mkdir(parents=True, exist_ok=True)
        except Exception as e:
            logger.warning(
                f"[IncidentManager] Could not create incidents dir "
                f"{self._incidents_dir}: {e}"
            )

        logger.info(
            f"[IncidentManager] Ready. storage={self._incidents_dir}"
        )

    # ──────────────────────────────────────────────────────────────────────────
    # Public API
    # ──────────────────────────────────────────────────────────────────────────

    @staticmethod
    def new_incident_id() -> str:
        """
        Generate a fresh incident ID.
        Format: INC-YYYYMMDD-<8 hex chars>
        Example: INC-20260517-a3f9c821

        Called by detection_engine/engine.py._new_incident_id().
        Kept here so the format is defined in one place.
        """
        date = datetime.now(timezone.utc).strftime("%Y%m%d")
        uid  = uuid.uuid4().hex[:8]
        return f"{INCIDENT_ID_PREFIX}-{date}-{uid}"

    def open(self, event: dict) -> Incident:
        """
        Register a new incident from a detection event.
        If the incident_id is already tracked (e.g. a repeat event for the
        same incident), returns the existing Incident without creating a
        duplicate.

        Args:
            event: enriched event dict from DetectionEngine.process_event()
                   Must contain 'incident_id'.

        Returns:
            The Incident object (new or existing).
        """
        incident_id = event.get("incident_id")
        if not incident_id:
            raise ValueError("event must contain 'incident_id'")

        with self._lock:
            if incident_id in self._incidents:
                logger.debug(
                    f"[IncidentManager] Incident already tracked: {incident_id}"
                )
                return self._incidents[incident_id]

            incident = Incident(event)
            self._incidents[incident_id] = incident
            self._persist(incident)

            logger.info(
                f"[IncidentManager] Opened: {incident_id} "
                f"level={incident.threat_level} "
                f"score={incident.risk_score} "
                f"source={incident.source}"
            )
            return incident

    def transition(
        self,
        incident_id: str,
        new_state: str,
        reason: str = "",
        containment: Optional[dict] = None,
    ) -> bool:
        """
        Move an incident to a new state.

        Args:
            incident_id: the INC-... ID string
            new_state:   one of CONTAINED / DISMISSED / FAILED / CLOSED
            reason:      human-readable explanation (logged and stored)
            containment: the containment result dict (from ContainmentEngine)
                         stored on the incident for later reporting

        Returns:
            True if transition succeeded, False if invalid or unknown ID.
        """
        new_state = new_state.upper()
        if new_state not in _STATES:
            logger.error(
                f"[IncidentManager] Unknown target state '{new_state}' "
                f"for incident {incident_id}"
            )
            return False

        with self._lock:
            incident = self._incidents.get(incident_id)
            if incident is None:
                logger.error(
                    f"[IncidentManager] transition() called for unknown "
                    f"incident: {incident_id}"
                )
                return False

            if new_state not in _ALLOWED_TRANSITIONS.get(incident.state, set()):
                logger.error(
                    f"[IncidentManager] Invalid transition "
                    f"{incident.state} → {new_state} "
                    f"for incident {incident_id}"
                )
                return False

            old_state = incident.state
            now       = datetime.now(timezone.utc).isoformat()

            incident.state      = new_state
            incident.updated_at = now
            if containment is not None:
                incident.containment = containment

            incident.history.append({
                "ts":         now,
                "from_state": old_state,
                "to_state":   new_state,
                "reason":     reason or f"Transitioned to {new_state}",
            })

            self._persist(incident)

            logger.info(
                f"[IncidentManager] {incident_id}: "
                f"{old_state} → {new_state} ({reason})"
            )
            return True

    def close(self, incident_id: str, reason: str = "Analyst closed") -> bool:
        """Convenience method: transition any terminal state → CLOSED."""
        return self.transition(incident_id, "CLOSED", reason=reason)

    def add_note(self, incident_id: str, note: str) -> bool:
        """Append an analyst note to the incident record."""
        with self._lock:
            incident = self._incidents.get(incident_id)
            if incident is None:
                return False
            incident.notes.append(
                f"[{datetime.now(timezone.utc).isoformat()}] {note}"
            )
            self._persist(incident)
        return True

    # ──────────────────────────────────────────────────────────────────────────
    # Lookup helpers
    # ──────────────────────────────────────────────────────────────────────────

    def get(self, incident_id: str) -> Optional[Incident]:
        """Return the Incident object or None if not found."""
        with self._lock:
            return self._incidents.get(incident_id)

    def get_all(self) -> list[dict]:
        """Return all incidents as a list of dicts (sorted newest first)."""
        with self._lock:
            incidents = list(self._incidents.values())
        return sorted(
            [i.to_dict() for i in incidents],
            key=lambda x: x["created_at"],
            reverse=True,
        )

    def get_open(self) -> list[dict]:
        """Return all incidents in OPEN state."""
        with self._lock:
            return [
                i.to_dict()
                for i in self._incidents.values()
                if i.state == "OPEN"
            ]

    def count_by_state(self) -> dict[str, int]:
        """Return a dict of {state: count} for the dashboard."""
        with self._lock:
            counts: dict[str, int] = {s: 0 for s in _STATES}
            for incident in self._incidents.values():
                counts[incident.state] += 1
        return counts

    def total(self) -> int:
        """Total number of incidents tracked in memory."""
        with self._lock:
            return len(self._incidents)

    # ──────────────────────────────────────────────────────────────────────────
    # Persistence
    # ──────────────────────────────────────────────────────────────────────────

    def _persist(self, incident: Incident) -> None:
        """
        Write the incident to disk as JSON.
        Called inside the lock — do not call without holding self._lock.
        Failures are logged but never raised (persistence is best-effort in v1).
        """
        path = self._incidents_dir / f"{incident.incident_id}.json"
        try:
            tmp_path = path.with_suffix(".tmp")
            with open(tmp_path, "w", encoding="utf-8") as fh:
                json.dump(incident.to_dict(), fh, indent=2, default=str)
            tmp_path.replace(path)   # atomic rename on same filesystem
        except Exception as e:
            logger.error(
                f"[IncidentManager] Failed to persist {incident.incident_id}: {e}"
            )

    def load_from_disk(self) -> int:
        """
        On startup, read all existing incident JSON files from disk and
        populate the in-memory store.  Call this once from core/engine.py
        during startup if you want persistence across restarts.

        Returns the number of incidents loaded.
        """
        loaded = 0
        try:
            for path in self._incidents_dir.glob("INC-*.json"):
                try:
                    with open(path, encoding="utf-8") as fh:
                        data = json.load(fh)

                    # Reconstruct a minimal event dict so Incident.__init__ works,
                    # then overwrite all fields from the stored data.
                    synthetic_event = {
                        "incident_id":     data["incident_id"],
                        "timestamp":       data["created_at"],
                        "threat_level":    data.get("threat_level", "LOW"),
                        "risk_score":      data.get("risk_score", 0),
                        "threat_category": data.get("threat_category", "unknown"),
                        "source":          data.get("source", "unknown"),
                        "process_name":    data.get("process_name"),
                        "pid":             data.get("pid"),
                        "file_path":       data.get("file_path"),
                        "remote_ip":       data.get("remote_ip"),
                    }

                    incident = Incident(synthetic_event)
                    incident.state       = data.get("state", "OPEN")
                    incident.updated_at  = data.get("updated_at", incident.updated_at)
                    incident.containment = data.get("containment")
                    incident.notes       = data.get("notes", [])
                    incident.history     = data.get("history", incident.history)

                    with self._lock:
                        self._incidents[incident.incident_id] = incident

                    loaded += 1

                except Exception as e:
                    logger.warning(
                        f"[IncidentManager] Skipping corrupt incident file "
                        f"{path.name}: {e}"
                    )

        except Exception as e:
            logger.warning(
                f"[IncidentManager] Could not scan incidents dir: {e}"
            )

        if loaded:
            logger.info(
                f"[IncidentManager] Loaded {loaded} incidents from disk."
            )
        return loaded

    # ──────────────────────────────────────────────────────────────────────────
    # Diagnostics
    # ──────────────────────────────────────────────────────────────────────────

    def __repr__(self) -> str:
        counts = self.count_by_state()
        return (
            f"<IncidentManager total={self.total()} "
            f"open={counts['OPEN']} "
            f"contained={counts['CONTAINED']} "
            f"closed={counts['CLOSED']}>"
        )
